version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "81:81"
    networks:
      - proxy

networks:
  proxy:
    external: true